import type { Step } from "@/components/lesson/kit";

export const PROGRAM = [
  "#include <iostream>",
  "using namespace std;",
  "#define SIZE 5",
  "",
  "int q[SIZE];",
  "int front = -1, rear = -1;",
  "",
  "bool isFull() {",
  "    return (rear + 1) % SIZE == front;",
  "}",
  "bool isEmpty() {",
  "    return front == -1;",
  "}",
  "",
  "void enqueue(int x) {",
  "    if (isFull()) {",
  '        cout << "Queue is full" << endl;',
  "        return;",
  "    }",
  "    if (isEmpty()) front = 0;",
  "    rear = (rear + 1) % SIZE;",
  "    q[rear] = x;",
  "}",
  "",
  "int dequeue() {",
  "    if (isEmpty()) {",
  '        cout << "Queue is empty" << endl;',
  "        return -1;",
  "    }",
  "    int x = q[front];",
  "    if (front == rear) front = rear = -1;",
  "    else front = (front + 1) % SIZE;",
  "    return x;",
  "}",
  "",
  "void display() {",
  "    if (isEmpty()) return;",
  "    int i = front;",
  "    while (true) {",
  '        cout << q[i] << " ";',
  "        if (i == rear) break;",
  "        i = (i + 1) % SIZE;",
  "    }",
  "    cout << endl;",
  "}",
  "",
  "int main() {",
  "    for (int v = 10; v <= 50; v += 10)",
  "        enqueue(v);",
  "    enqueue(60);",
  '    cout << "Removed " << dequeue() << endl;',
  '    cout << "Removed " << dequeue() << endl;',
  "    enqueue(60);",
  "    enqueue(70);",
  "    display();",
  "    return 0;",
  "}",
];

/** Line numbers (0-based) the stage refers to. */
export const L = {
  include: 0,
  using: 1,
  define: 2,
  arr: 4,
  ptrs: 5,
  isFull: 7,
  isFullRet: 8,
  isEmpty: 10,
  isEmptyRet: 11,
  enq: 14,
  enqFull: 15,
  enqFullMsg: 16,
  enqFullRet: 17,
  enqFirst: 19,
  enqRear: 20,
  enqStore: 21,
  enqEnd: 22,
  deq: 24,
  deqEmpty: 25,
  deqTake: 29,
  deqLast: 30,
  deqFront: 31,
  deqRet: 32,
  deqEnd: 33,
  disp: 35,
  dispEmpty: 36,
  dispI: 37,
  dispWhile: 38,
  dispPrint: 39,
  dispIf: 40,
  dispInc: 41,
  dispClose: 42,
  dispEndl: 43,
  dispEnd: 44,
  main: 46,
  loop: 47,
  loopCall: 48,
  full: 49,
  deq1: 50,
  deq2: 51,
  enq60: 52,
  enq70: 53,
  show: 54,
  ret: 55,
  end: 56,
};

export const SIZE = 5;
/** First value each slot receives, and the value it is overwritten with after wrapping. */
export const FIRST = [10, 20, 30, 40, 50];
export const SECOND: (number | null)[] = [60, 70, null, null, null];
/** display() walks from front to rear, wrapping. */
export const WALK = [2, 3, 4, 0, 1];
export const SHOWN = WALK.map((s) => SECOND[s] ?? FIRST[s]);

export const STEPS: Step[] = [
  {
    w: 1,
    kicker: "Lines 3 – 6",
    title: "A queue in an array",
    body: [
      "A queue is first in, first out: the first value added is the first one removed, like a line at a ticket counter.",
      "We keep it in a plain array of 5, with two markers: front (who leaves next) and rear (who arrived last). -1 means the queue is empty.",
    ],
    note: "Add at the rear, remove from the front. Never the other way round.",
  },
  {
    w: 1.8,
    kicker: "The problem",
    title: "A straight line wastes space",
    body: [
      "Fill all 5, then remove two. front moves right to box 2, but rear is stuck at the last box.",
      "Now rear + 1 == SIZE, so the queue says it's full, even though boxes 0 and 1 are empty.",
    ],
    note: "In a straight-line queue, removed boxes can never be used again.",
  },
  {
    w: 1.4,
    kicker: "The fix",
    title: "Bend it into a ring",
    body: [
      "Join the end of the array back to the start. After box 4 comes box 0 again.",
      "The array doesn't change; only how we move through it. The next index is always (i + 1) % SIZE, and (4 + 1) % 5 = 0.",
    ],
    note: "% gives the remainder. It keeps any index inside 0 … SIZE − 1.",
  },
  {
    w: 1,
    kicker: "Lines 8 – 13",
    title: "Two questions: full? empty?",
    body: [
      "Empty is easy: front == -1.",
      "Full means the box after rear is front. The rear has gone all the way round and caught up with the front.",
    ],
    note: "Both are small functions so enqueue and dequeue read like English: if (isFull()) …",
  },
  {
    w: 4.3,
    kicker: "Lines 15 – 23",
    title: "enqueue: add at the rear",
    body: [
      "Check isFull first. If the queue was empty, front becomes 0.",
      "Then move rear one step round the ring and store the value there. main adds 10, 20, 30, 40 and 50.",
    ],
    note: "rear = (rear + 1) % SIZE is the whole trick. Every move uses it.",
  },
  {
    w: 1.3,
    kicker: "Line 50",
    title: "Full is full",
    body: [
      "enqueue(60): rear is 4 and (4 + 1) % 5 = 0, which equals front. isFull() is true.",
      "The function prints a message and returns before touching the array.",
    ],
    note: "Adding to a full queue is called overflow.",
  },
  {
    w: 2.1,
    kicker: "Lines 25 – 34",
    title: "dequeue: remove from the front",
    body: [
      "Take q[front], then move front one step round the ring. 10 leaves, then 20.",
      "The old values stay in their boxes, but they're outside front … rear now, so they don't count.",
    ],
    note: "If front == rear, that was the last element: reset both to -1 so the queue is empty again.",
  },
  {
    w: 1.6,
    kicker: "Lines 53 – 54",
    title: "Round the corner",
    body: [
      "enqueue(60) again. rear is 4, and (4 + 1) % 5 = 0, but this time front is 2, so there's room.",
      "rear wraps round to box 0 and reuses it. Then 70 goes into box 1. No space is wasted.",
    ],
    note: "This wrap-around is the whole reason a circular queue exists.",
  },
  {
    w: 2.4,
    kicker: "Lines 36 – 45",
    title: "display: walk from front to rear",
    body: [
      "i starts at front and moves with the same % rule until it reaches rear: boxes 2, 3, 4, 0, 1.",
      "So the queue prints in arrival order, 30 40 50 60 70, even though 60 and 70 sit at the start of the array.",
    ],
    note: "Don't loop i from 0 to SIZE − 1: you'd print the queue in the wrong order.",
  },
  {
    w: 1,
    kicker: "Why it's good",
    title: "Solved",
    body: [
      "enqueue and dequeue never shift anything. They move one marker, so both take O(1) time.",
      "Every box can be reused forever, so a queue of SIZE boxes really holds SIZE values.",
    ],
    note: "Exam tip: always write the full condition (rear + 1) % SIZE == front and explain the wrap-around with a diagram.",
  },
];
