import type { Step } from "@/components/lesson/kit";

export const PROGRAM = [
  "#include <iostream>",
  "using namespace std;",
  "",
  "struct Node {",
  "    int data;",
  "    Node* next;",
  "};",
  "",
  "Node* newNode(int x) {",
  "    Node* p = new Node;",
  "    p->data = x;",
  "    p->next = NULL;",
  "    return p;",
  "}",
  "",
  "void insertBegin(Node*& head, int x) {",
  "    Node* p = newNode(x);",
  "    p->next = head;",
  "    head = p;",
  "}",
  "",
  "void insertEnd(Node*& head, int x) {",
  "    Node* p = newNode(x);",
  "    if (head == NULL) { head = p; return; }",
  "    Node* t = head;",
  "    while (t->next != NULL) t = t->next;",
  "    t->next = p;",
  "}",
  "",
  "void insertAt(Node*& head, int x, int pos) {",
  "    if (pos == 0) {",
  "        insertBegin(head, x);",
  "        return;",
  "    }",
  "    Node* t = head;",
  "    for (int i = 1; i < pos && t != NULL; i++)",
  "        t = t->next;",
  "    if (t == NULL) {",
  '        cout << "Invalid position" << endl;',
  "        return;",
  "    }",
  "    Node* p = newNode(x);",
  "    p->next = t->next;",
  "    t->next = p;",
  "}",
  "",
  "void display(Node* head) {",
  "    for (Node* t = head; t != NULL; t = t->next)",
  '        cout << t->data << " -> ";',
  '    cout << "NULL" << endl;',
  "}",
  "",
  "int main() {",
  "    Node* head = NULL;",
  "    insertEnd(head, 20);",
  "    insertEnd(head, 40);",
  "    insertBegin(head, 10);",
  "    insertAt(head, 30, 2);",
  "    display(head);",
  "    return 0;",
  "}",
];

/** Line numbers (0-based) the stage refers to. */
export const L = {
  include: 0,
  struct: 3,
  structEnd: 6,
  nn: 8,
  nnAlloc: 9,
  nnData: 10,
  nnNull: 11,
  nnRet: 12,
  nnEnd: 13,
  ib: 15,
  ibNew: 16,
  ibLink: 17,
  ibHead: 18,
  ibEnd: 19,
  ie: 21,
  ieNew: 22,
  ieEmpty: 23,
  ieT: 24,
  ieWalk: 25,
  ieLink: 26,
  ieEnd: 27,
  ia: 29,
  iaZero: 30,
  iaT: 34,
  iaFor: 35,
  iaHop: 36,
  iaNull: 37,
  iaNew: 41,
  iaLink1: 42,
  iaLink2: 43,
  iaEnd: 44,
  disp: 46,
  dispFor: 47,
  dispPrint: 48,
  dispNull: 49,
  dispEnd: 50,
  main: 52,
  mHead: 53,
  call1: 54,
  call2: 55,
  call3: 56,
  call4: 57,
  call5: 58,
  mRet: 59,
  end: 60,
};

/** Nodes in the order they are created. */
export const NODES = [
  { key: "A", v: 20, addr: "0x5A0", x: 0.34, y: 0.02 },
  { key: "B", v: 40, addr: "0x6C8", x: 0.72, y: 0.3 },
  { key: "C", v: 10, addr: "0x4E0", x: 0.0, y: 0.3 },
  { key: "D", v: 30, addr: "0x7B8", x: 0.38, y: 0.66 },
];
export const A = 0;
export const B = 1;
export const C = 2;
export const D = 3;
/** Final order: C → A → D → B. */
export const ORDER = [C, A, D, B];
export const OUTPUT = `${ORDER.map((k) => NODES[k].v).join(" -> ")} -> NULL`;

export const STEPS: Step[] = [
  {
    w: 1.1,
    kicker: "Lines 4 – 14",
    title: "A helper that makes nodes",
    body: [
      "Every insert needs a fresh node, so newNode(x) does the work once: new, set data, set next to NULL, return the address.",
      "main starts with an empty list: head = NULL.",
    ],
    note: "Three insert functions below will all call newNode. Write it once, use it everywhere.",
  },
  {
    w: 1.5,
    kicker: "Lines 22 – 28 · line 55",
    title: "insertEnd on an empty list",
    body: [
      "insertEnd(head, 20) gets a new node. The list is empty, so the new node simply becomes head.",
      "Look at the parameter: Node*& head. The & makes it a reference, so the function's head is main's head. When the function sets head, main sees it.",
    ],
    note: "Without the &, the function would change its own copy and main's head would stay NULL.",
  },
  {
    w: 1.4,
    kicker: "Line 56",
    title: "insertEnd: walk to the last node",
    body: [
      "insertEnd(head, 40). Now the list isn't empty, so t starts at head and walks while t->next != NULL.",
      "With one node the walk stops at once. Then t->next = p hooks the new node on.",
    ],
    note: "There's no tail pointer here, so every insertEnd walks the whole list: O(n).",
  },
  {
    w: 1.4,
    kicker: "Lines 16 – 20 · line 57",
    title: "insertBegin: no walking at all",
    body: [
      "insertBegin(head, 10). Two lines: the new node points at the current first node (p->next = head), then head moves to the new node (head = p).",
      "Nothing else in the list is touched. That's why inserting at the front of a linked list is O(1), unlike an array.",
    ],
    note: "Order matters: if head = p ran first, p->next = head would point the node at itself.",
  },
  {
    w: 2.4,
    kicker: "Lines 30 – 45 · line 58",
    title: "insertAt: stop one node early",
    body: [
      "insertAt(head, 30, 2) must put 30 at position 2. To link it in we need the node before that spot, so t walks pos − 1 = 1 step: from 10 to 20.",
      "Then two pointer changes: the new node points where t pointed (p->next = t->next), and t points to the new node (t->next = p).",
    ],
    note: "If t runs off the end (t == NULL), the position doesn't exist. Report it and stop.",
  },
  {
    w: 1,
    kicker: "A trap",
    title: "Swap those two lines and…",
    body: [
      "Suppose t->next = p ran first. Then p->next = t->next copies p's own address: the node points at itself.",
      "Nothing points to 40 any more. It's still in memory but can never be reached. That's called a memory leak.",
    ],
    note: "Always connect the new node to the rest of the list before cutting the old link.",
  },
  {
    w: 2.5,
    kicker: "Lines 47 – 51 · line 59",
    title: "display: 10 20 30 40",
    body: [
      "display takes head by value, a plain copy, because it only reads the list.",
      "Following the arrows from head gives 10 -> 20 -> 30 -> 40 -> NULL, even though the nodes were created as 20, 40, 10, 30.",
    ],
    note: "The order of a linked list is the order of its arrows, not the order of creation or of addresses.",
  },
  {
    w: 1,
    kicker: "Cost",
    title: "Front is free, end walks",
    body: [
      "insertBegin changes two pointers: O(1). insertEnd walks to the last node: O(n). insertAt walks pos − 1 nodes: O(pos).",
      "That's the reverse of an array, where the end was cheap and the front was expensive.",
    ],
    note: "Keep a tail pointer (as in Question 7) and insertEnd becomes O(1) too.",
  },
];
