import type { Step } from "@/components/lesson/kit";

export const PROGRAM = [
  "#include <iostream>",
  "using namespace std;",
  "",
  "struct Node {",
  "    int data;",
  "    Node* next;",
  "};",
  "",
  "void insertEnd(Node*& head, int x) {",
  "    Node* p = new Node{x, NULL};",
  "    if (head == NULL) { head = p; return; }",
  "    Node* t = head;",
  "    while (t->next != NULL) t = t->next;",
  "    t->next = p;",
  "}",
  "",
  "void deleteBegin(Node*& head) {",
  "    if (head == NULL) return;",
  "    Node* p = head;",
  "    head = head->next;",
  "    delete p;",
  "}",
  "",
  "void deleteEnd(Node*& head) {",
  "    if (head == NULL) return;",
  "    if (head->next == NULL) {",
  "        delete head;",
  "        head = NULL;",
  "        return;",
  "    }",
  "    Node* t = head;",
  "    while (t->next->next != NULL) t = t->next;",
  "    delete t->next;",
  "    t->next = NULL;",
  "}",
  "",
  "void deleteAt(Node*& head, int pos) {",
  "    if (pos == 0) {",
  "        deleteBegin(head);",
  "        return;",
  "    }",
  "    Node* t = head;",
  "    for (int i = 1; i < pos && t != NULL; i++)",
  "        t = t->next;",
  "    if (t == NULL || t->next == NULL) {",
  '        cout << "Invalid position" << endl;',
  "        return;",
  "    }",
  "    Node* p = t->next;",
  "    t->next = p->next;",
  "    delete p;",
  "}",
  "",
  "void display(Node* head) {",
  "    for (Node* t = head; t != NULL; t = t->next)",
  '        cout << t->data << " -> ";',
  '    cout << "NULL" << endl;',
  "}",
  "",
  "int main() {",
  "    Node* head = NULL;",
  "    for (int v = 10; v <= 50; v += 10)",
  "        insertEnd(head, v);",
  "    display(head);",
  "    deleteBegin(head);",
  "    deleteEnd(head);",
  "    deleteAt(head, 1);",
  "    display(head);",
  "    return 0;",
  "}",
];

/** Line numbers (0-based) the stage refers to. */
export const L = {
  include: 0,
  struct: 3,
  structEnd: 6,
  ie: 8,
  ieEnd: 14,
  db: 16,
  dbEmpty: 17,
  dbP: 18,
  dbHead: 19,
  dbDelete: 20,
  dbEnd: 21,
  de: 23,
  deEmpty: 24,
  deOne: 25,
  deT: 30,
  deWalk: 31,
  deDelete: 32,
  deNull: 33,
  deEnd: 34,
  da: 36,
  daZero: 37,
  daT: 41,
  daFor: 42,
  daHop: 43,
  daCheck: 44,
  daP: 48,
  daBypass: 49,
  daDelete: 50,
  daEnd: 51,
  disp: 53,
  dispFor: 54,
  dispPrint: 55,
  dispNull: 56,
  dispEnd: 57,
  main: 59,
  mHead: 60,
  mLoop: 61,
  mCall: 62,
  show1: 63,
  delB: 64,
  delE: 65,
  delAt: 66,
  show2: 67,
  mRet: 68,
  end: 69,
};

export const NODES = [
  { v: 10, addr: "0x5A0", x: 0.0, y: 0.1 },
  { v: 20, addr: "0x6C8", x: 0.3, y: 0.0 },
  { v: 30, addr: "0x4E0", x: 0.62, y: 0.12 },
  { v: 40, addr: "0x7B8", x: 0.3, y: 0.6 },
  { v: 50, addr: "0x3F0", x: 0.64, y: 0.68 },
];
export const OUT1 = `${NODES.map((n) => n.v).join(" -> ")} -> NULL`;
export const OUT2 = "20 -> 40 -> NULL";

export const STEPS: Step[] = [
  {
    w: 1.4,
    kicker: "Lines 9 – 15 · 61 – 63",
    title: "Something to delete from",
    body: [
      "main builds 10 → 20 → 30 → 40 → 50 with the insertEnd from Question 8.",
      "Every node came from new, so every node must eventually be given back with delete.",
    ],
    note: "new takes memory from the heap. delete returns it. Each new needs exactly one delete.",
  },
  {
    w: 2.7,
    kicker: "Line 64",
    title: "display before deleting",
    body: ["A quick walk from head so we can compare later: 10 -> 20 -> 30 -> 40 -> 50 -> NULL."],
    note: "Same display as before: it gets a copy of head and follows the arrows.",
  },
  {
    w: 1.4,
    kicker: "Lines 17 – 22 · 65",
    title: "deleteBegin: move head, then free",
    body: [
      "Keep the first node in p, move head to the second node, then delete p.",
      "The order matters. If you delete first, head->next reads memory that no longer belongs to you.",
    ],
    note: "Deleting the first node is O(1): no walking, one pointer changes.",
  },
  {
    w: 2.2,
    kicker: "Lines 24 – 35 · 66",
    title: "deleteEnd: stop at the second-last node",
    body: [
      "To remove the last node we must change the next of the node before it, so t walks while t->next->next != NULL.",
      "After delete t->next, that next field still holds the old address: a dangling pointer to freed memory. t->next = NULL makes it the new end.",
    ],
    note: "Skipping t->next = NULL leaves the list pointing at freed memory. The next display would crash or print garbage.",
  },
  {
    w: 1.8,
    kicker: "Lines 37 – 52 · 67",
    title: "deleteAt: go round it, then free it",
    body: [
      "deleteAt(head, 1) removes the node at position 1. t stops one before it, at 20. p is the victim, 30.",
      "t->next = p->next makes 20 point straight to 40, skipping 30. Only then is p deleted.",
    ],
    note: "The check t->next == NULL catches a position past the end: there'd be nothing to delete.",
  },
  {
    w: 1.6,
    kicker: "Line 68",
    title: "display after deleting",
    body: [
      "From head the arrows now give 20 -> 40 -> NULL.",
      "The freed nodes are still drawn faintly, but nothing points to them and they're not ours any more.",
    ],
    note: "A deleted node isn't wiped; its memory is just handed back for new to reuse.",
  },
  {
    w: 1,
    kicker: "Cost",
    title: "Relink, then delete",
    body: [
      "deleteBegin is O(1). deleteEnd walks to the second-last node: O(n). deleteAt walks pos − 1 nodes: O(pos).",
      "Every delete follows the same rule: fix the arrows first, then free the node.",
    ],
    note: "Compare arrays: removing the first element shifted everything (Question 3). Here it's one pointer.",
  },
];
